### PR TITLE
Date <-> ZonedDateTime

### LINKED ISSUE #222: Add Date(::ZonedDateTime) method
There is a `DateTime(::ZonedDateTime)` method, but no `Date(::ZonedDateTime)` method:

```julia
julia> using Dates, TimeZones

julia> t = ZonedDateTime(2014, 7, 15, 14, 35, 46, tz"America/Chicago")
2014-07-15T14:35:46-05:00

julia> DateTime(t)
2014-07-15T14:35:46

julia> Date(t)
ERROR: MethodError: Cannot `convert` an object of type ZonedDateTime to an object of type Date
Closest candidates are:
  convert(::Type{Date}, ::DateTime) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Dates/src/conversions.jl:31
  convert(::Type{Date}, ::Day) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Dates/src/conversions.jl:36
  convert(::Type{T}, ::T) where T at essentials.jl:154
  ...
Stacktrace:
 [1] Date(::ZonedDateTime) at /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.1/Dates/src/conversions.jl:12
 [2] top-level scope at none:0
```

Desired behavior:

```julia
julia> Date(zdt::ZonedDateTime) = Date(DateTime(zdt))
Date

julia> Date(t)
2014-07-15
```

In other words, I expect that `DateTime` truncates the time zone information from a zoned date time and `Date` truncates both the time zone information and the hour-minute-seconds information.

### PR DESCRIPTION
**Pull request by oxinabox**
I got really tired of writing `Date(DateTime(zdt))` and `ZonedDateTime(DateTime(date))`

Fixes #222 and #209 

```
julia> zdt = ZonedDateTime(Date(2011, 6, 1), tz"America/Winnipeg")
2011-06-01T00:00:00-05:00

julia> Date(zdt)
2011-06-01

julia> DateTime(Date(2011, 6, 1))
2011-06-01T00:00:00
```

### CODE REVIEW

File: src/conversions.jl [hunk 1]
```diff
@@ -11,6 +11,14 @@ Returns an equivalent `DateTime` without any `TimeZone` information.
 """
 DateTime(zdt::ZonedDateTime) = localtime(zdt)
 
+"""
+    Date(::ZonedDateTime) -> Date
+
+Returns an equivalent `Date` without any `TimeZone`, or time information.
+"""
+Dates.Date(zdt::ZonedDateTime) = Date(DateTime(zdt))
```
Comment (omus) [inline src/conversions.jl]: I've been intending on dropping `DateTime(::ZonedDateTime)` in favor of `localtime(::Type{DateTime}, ::ZonedDateTime)` or something similar. This is definitely a lossy operation and it's important to communicate the implicit time zone.

File: test/conversions.jl [hunk 2]
```diff
@@ -6,28 +6,34 @@ warsaw = first(compile("Europe/Warsaw", tzdata["europe"]))
...
-zdt = ZonedDateTime(dt, warsaw)
-@test DateTime(zdt) == dt
-
-# Converting from ZonedDateTime to DateTime isn't possible as it is always inexact.
-@test_throws MethodError convert(DateTime, zdt)
-
-# Vectorized accessors
-n = 10
-arr = fill(zdt, n)
-@test Dates.DateTime.(arr) == fill(dt, n)
```
Comment (fchorney) [inline test/conversions.jl]: we don't want this test anymore?

File: test/conversions.jl [hunk 3]
```diff
@@ -6,28 +6,34 @@ warsaw = first(compile("Europe/Warsaw", tzdata["europe"]))
...
-# now function
-dt = now(Dates.UTC)::DateTime
-zdt = now(warsaw)
-@test zdt.timezone == warsaw
-@test Dates.datetime2unix(TimeZones.utc(zdt)) ≈ Dates.datetime2unix(dt)
-
-# today function
-@test abs(today() - today(warsaw)) <= Dates.Day(1)
-@test today(apia) - today(midway) == Dates.Day(1)
+@testset "Between ZonedDateTime and DateTime" begin
```
Comment (omus) [inline test/conversions.jl]:
```suggestion
@testset "Construct ZonedDateTime / DateTime" begin
```

File: test/conversions.jl [hunk 4]
```diff
@@ -6,28 +6,34 @@ warsaw = first(compile("Europe/Warsaw", tzdata["europe"]))
...
+    # Constructing a ZonedDateTime from a DateTime and the reverse
+    dt = DateTime(2015, 1, 1, 0)
+    zdt = ZonedDateTime(dt, warsaw)
+    @test DateTime(zdt) == dt
+
+    # Converting from ZonedDateTime to DateTime isn't possible as it is always inexact.
+    @test_throws MethodError convert(DateTime, zdt)
+end
+
+@testset "Between Date and ZonedDateTime" begin
```
Comment (omus) [inline test/conversions.jl]:
```suggestion
@testset "Construct Date / ZonedDateTime" begin
```

File: test/conversions.jl (hunk 2 above)
Comment (oxinabox) [reply test/conversions.jl]: Isn't this just testing that broadcasting works?
Testing that broadcasting works on arrays is not our problem.

This test is leftover from ancient times  (https://github.com/JuliaTime/TimeZones.jl/pull/7)
when `DateTime(::Vector{ZonedDateTime})` was defined.
And so needed tests.
But we got rid of that because julia gained broadcasting,
and I guess the test just got converted over to use the new broadcasting,
without realizing that the code it was suppose to test didn't exist anymore.

File: src/conversions.jl (hunk 1 above)
Comment (omus) [reply src/conversions.jl]: https://github.com/JuliaTime/TimeZones.jl/issues/125

Comment (oxinabox) [reply src/conversions.jl]: I would really dislike that.
Often I just have a collection of `DateTime`,
one per day.
and I want to plot them (cf #184),
or I want to display them in a table,
and I just want to get rid of extra information.
I don't actually care about the time or even the exact date often.

I think it pretty clear to the user that  it is losing information.

Comment (omus) [reply src/conversions.jl]: Looking at that issue again `Date(zdt, UTC)` / `Date(zdt, Local)` isn't bad

File: test/conversions.jl (hunk 2 above)
Comment (omus) [reply test/conversions.jl]: We can drop this code now

File: src/conversions.jl (hunk 1 above)
Comment (oxinabox) [reply src/conversions.jl]: I am happy to see this change when we resolve #125 for `DateTime`s.
Til then this match the API we have

Comment (omus) [reply src/conversions.jl]: Let's just make the change now? Both the `UTC` and `Local` types already exist

Comment (omus) [reply src/conversions.jl]: If you don't want to take on the change yourself I can make the remainder of the changes. I don't think I would merge this as is.

Comment (oxinabox) [reply src/conversions.jl]: I do want to merge as is, because the status quo of matching how `DateTime` works is known.
All other things are not known and we might want to do a little design and thinking.

### OTOH:
 - `Date(zdt, Local)` and `Date(zdt, UTC)` // `DateTime(zdt, Local)` and `DateTime(zdt, UTC)` do sound right to me though.
 - A bunch of places that do `DateTime(ztd)` will need to be changed due to deprecation. and any places that do `Date(DateTime(ztd))` will be a subset of those. So doing both at once would mean  we can go staight to `Date(ztd, Local)`. 

I think I am convinced.

Comment (omus) [reply src/conversions.jl]: > I think I am convinced

Convinced enough to do the work? ;). As I said I can do the leg work if you prefer.

Comment (oxinabox) [reply src/conversions.jl]: I'm not sure how deep I would have to go,
so if you know exactly what you have to change be my guest.

Otherwise this might sit til after neurips

Comment (oxinabox) [reply src/conversions.jl]: Waiting til after NeurIPS might be fine though.
We've lived this long

**Comment by omus** [comment]
Alright, I've made the updates and bumped the version to 1.0.0 (it's time)

File: src/TimeZones.jl [hunk 5]
```diff
@@ -4,10 +4,12 @@ using Dates
 using Printf
 using Serialization
 using Unicode
-import Dates: TimeZone
+
+import Dates: TimeZone, UTC
```
Comment (oxinabox) [inline src/TimeZones.jl]: Lets not make more of this violation of BlueStyle?

```suggestion
import Dates: TimeZone
using: Dates: UTC
```

File: src/adjusters.jl [hunk 6]
```diff
@@ -6,10 +6,10 @@ using Dates: DatePeriod, TimePeriod, firstdayofweek, lastdayofweek,
 # Truncation
 # TODO: Just utilize floor code for truncation?
 function Base.trunc(zdt::ZonedDateTime, ::Type{P}) where P <: DatePeriod
-    ZonedDateTime(trunc(localtime(zdt), P), timezone(zdt))
+    ZonedDateTime(trunc(DateTime(zdt, Local), P), timezone(zdt))
```
Comment (oxinabox) [inline src/adjusters.jl]:
```suggestion
    return ZonedDateTime(trunc(DateTime(zdt, Local), P), timezone(zdt))
```

File: src/adjusters.jl [hunk 7]
```diff
@@ -18,7 +18,7 @@ Base.trunc(zdt::ZonedDateTime, ::Type{Millisecond}) = zdt
 # Adjusters
 for prefix in ("firstdayof", "lastdayof"), suffix in ("week", "month", "year", "quarter")
     func = Symbol(prefix * suffix)
-    @eval begin
-        Dates.$func(dt::ZonedDateTime) = ZonedDateTime($func(localtime(dt)), dt.timezone)
+    @eval function Dates.$func(zdt::ZonedDateTime)
+        ZonedDateTime($func(DateTime(zdt, Local)), zdt.timezone)
```
Comment (oxinabox) [inline src/adjusters.jl]:
```suggestion
        return ZonedDateTime($func(DateTime(zdt, Local)), zdt.timezone)
```

File: src/adjusters.jl [hunk 8]
```diff
@@ -18,7 +18,7 @@ Base.trunc(zdt::ZonedDateTime, ::Type{Millisecond}) = zdt
 # Adjusters
 for prefix in ("firstdayof", "lastdayof"), suffix in ("week", "month", "year", "quarter")
     func = Symbol(prefix * suffix)
```
Comment (oxinabox) [inline src/adjusters.jl]: Not related but is it cleaner to do:

```suggestion
    func = Symbol(prefix, suffix)
```

File: src/deprecated.jl [hunk 9]
```diff
@@ -1,7 +1,9 @@
-using Base: @deprecate, @deprecate_binding
+using Base: @deprecate
 
-# BEGIN TimeZones 0.9 deprecations
+# BEGIN TimeZones 1.0 deprecations
```
Comment (oxinabox) [inline src/deprecated.jl]: 1.0, huh

File: src/TimeZones.jl (hunk 5 above)
Comment (omus) [reply src/TimeZones.jl]: How does this violate it?

File: src/deprecated.jl (hunk 9 above)
Comment (omus) [reply src/deprecated.jl]: It's time. I usually don't make API breaking changes but I use minor versions to indicate features.

File: src/TimeZones.jl (hunk 5 above)
Comment (oxinabox) [reply src/TimeZones.jl]: We have a guideline against using `import` ever.

Comment (omus) [reply src/TimeZones.jl]: In this particular case I like the use of `import` as these are concepts that would make sense to be defined in TimeZones.jl but are currently in the Dates stdlib. By using `import` I'm explicitly calling out the special relationship here.

File: src/conversions.jl [hunk 10]
```diff
@@ -90,31 +155,31 @@ function astimezone(zdt::ZonedDateTime, tz::FixedTimeZone)
...
 end
 
 function zdt2unix(::Type{T}, zdt::ZonedDateTime) where T<:Integer
-    floor(T, datetime2unix(utc(zdt)))
+    floor(T, datetime2unix(DateTime(zdt, UTC)))
 end
 
 function zdt2unix(::Type{T}, zdt::ZonedDateTime) where T<:Real
-    convert(T, datetime2unix(utc(zdt)))
+    convert(T, datetime2unix(DateTime(zdt, UTC)))
```
[the remark this answers is not in the document]
Comment (omus) [reply src/conversions.jl]: Let's keep the addition of `return` statements to a separate PR otherwise this PR could become held up.

[the remark this answers is not in the document]
Comment (omus) [reply src/conversions.jl]: https://github.com/invenia/BlueStyle/issues/43

[the remark this answers is not in the document]
Comment (oxinabox) [reply src/conversions.jl]: I don't see why clicking "apply" would hold this up.
No need to go do the others I've missed but might as well get these ones.

[the remark this answers is not in the document]
Comment (omus) [reply src/conversions.jl]: What I mean is I'm good with these changes without the applying the `return` statements

**Comment by omus** [comment]
I squashed some commits in preparation for merging. A couple of things to note:
- Adding return statements will not be done in this PR as I think that is a separate conversation
- We're bumping to version 1.0 here as there haven't been any major API changes for a while and the ones I have planned can always go into 2.0

File: src/conversions.jl (hunk 10 above)
[the remark this answers is not in the document]
Comment (oxinabox) [reply src/conversions.jl]: what I mean is:
Rather than having this discussion, you can click "Commit suggestion" above.
And that will take less time than concluding the discussion.

[the remark this answers is not in the document]
Comment (oxinabox) [reply src/conversions.jl]: Transfering from slack:

@omus  said:
> In the case of a disagreement follow the status quo of what is currently present in the repo 

I said:
> That is an important distinction that I failed to take into account.
> I am now convinced.

File: src/TimeZones.jl (hunk 5 above)
Comment (oxinabox) [reply src/TimeZones.jl]: Ok thats fair

File: src/conversions.jl [hunk 11]
```diff
@@ -5,11 +5,76 @@ using Mocking: Mocking, @mock
...
+Date(::ZonedDateTime, ::Union{Type{Local}, Type{UTC}})
+
+Dates.Date(zdt::ZonedDateTime, ::Type{Local}) = Date(DateTime(zdt, Local))
+Dates.Date(zdt::ZonedDateTime, ::Type{UTC}) = Date(DateTime(zdt, UTC))
+
+
+"""
+    Time(zdt::ZonedDateTime, ::Union{Type{Local}, Type{UTC}}) -> Time
+
+Create an implicit local/UTC `Time` from the given `ZonedDateTime`.
```
Comment (oxinabox) [inline src/conversions.jl]: Couild we add a bit more text?

```suggestion
Create an implicit local/UTC `Time` from the given `ZonedDateTime`.

 - `Local` means a time local to the timezone in the `ZonedDateTime`, i.e. just discarding the timezone information. (**Not** local to the system time of the user invoking the code).
  - `UTC` means to shift to the `UTC` timezone and then discard all timezone information.
```

Maybe also this particular text should be put in to a string constant and interpolatred in at a few places?
Like in `Date` and `DateTime` as well?

Probably could be written better

Comment (omus) [reply src/conversions.jl]: I rewrote the docstrings to be more sensible

Comment (omus) [reply src/conversions.jl]: I rewrote the docstrings to be more sensible

**Comment by omus** [comment]
Quick note: I'm still planning on doing the 1.0 version change as part of this but since this adds a deprecation I'll be doing a 0.11 release first so I can drop the deprecation as part of 1.0

File: src/discovery.jl [hunk 12]
```diff
@@ -158,13 +158,13 @@ function next_transition_instant(zdt::ZonedDateTime)
...
     index = searchsortedfirst(
-        tz.transitions, TimeZones.utc(zdt),
+        tz.transitions, DateTime(zdt, UTC),
         by=el -> isa(el, TimeZones.Transition) ? el.utc_datetime : el,
     )
 
     index <= length(tz.transitions) || return nothing
 
-    # Use the UTC datetime of the transition and the offset information prior to the
+    # Use the UTC daftetime of the transition and the offset information prior to the
```
Comment (mattBrzezinski) [inline src/discovery.jl]:
```suggestion
    # Use the UTC datetime of the transition and the offset information prior to the
```

File: src/TimeZones.jl [hunk 13]
```diff
@@ -4,10 +4,12 @@ using Dates
...
 
 export TimeZone, @tz_str, istimezone, FixedTimeZone, VariableTimeZone, ZonedDateTime,
-    DateTime, TimeError, AmbiguousTimeError, NonExistentTimeError, UnhandledTimeError,
+    DateTime, Date, Time, UTC, Local, TimeError, AmbiguousTimeError, NonExistentTimeError,
```
[the remark this answers is not in the document]
Comment (omus) [reply src/TimeZones.jl]: I can do some organization. What do you think of grouping by the file in which these are defined (and having a comment indicating the file)

[the remark this answers is not in the document]
Comment (mattBrzezinski) [reply src/TimeZones.jl]: This might be too granular, but:

```
export @tz_str
export AmbiguousTimeError, NonExistentTimeError, TimeError
export Date, DateTime, Local, Time, TimeZone, UTC, VariableTimeZone, ZonedDateTime
export isdatetime
```

I think it's less about what the groupings are but more that there is some order to them.

[the remark this answers is not in the document]
Comment (omus) [reply src/TimeZones.jl]: I'll note that there is an ordering to this but it's not as obvious as I'd like. A couple of key things I would like to communicate as part of the exports:
- Quite a few of these are re-exports from `Dates` which are just here in case someone only does `using TimeZones`
- There are some types that are closely related like `UTC` and `Local` which I think should be sequential

I'll post an revised version in a sec

[the remark this answers is not in the document]
Comment (omus) [reply src/TimeZones.jl]: What I'm currently thinking:
```julia
export
    TimeZone, FixedTimeZone, VariableTimeZone, @tz_str, istimezone, localzone
    UTC, Local,
    ZonedDateTime, timezone,

    # Exceptions
    TimeError, AmbiguousTimeError, NonExistentTimeError, UnhandledTimeError,

    # Discovery tools
    timezone_names, all_timezones, timezones_from_abbr, timezone_abbrs,
    next_transition_instant, show_next_transition,

    # Extended functionality from Dates. Note: Some of these exports have already been done
    # but are listed here for completeness.
    TimeZone, UTC,
    DateTime, Date, Time,
    now, today,
    year, month, week, day, dayofmonth, hour, minute, second, millisecond
    yearmonthday, yearmonth, monthday,
    firstdayofyear, firstdayofquarter, firstdayofmonth, firstdayofweek,
    lastdayofyear, lastdayofquarter, lastdayofmonth, lastdayofweek
```
I'm unsure on what is better at this point and possibly this kind of logical grouping should just be in the documentation? In any case I think this could be made into an issue and not hold up this PR.

[the remark this answers is not in the document]
Comment (mattBrzezinski) [reply src/TimeZones.jl]: Agreed, this isn't a dealbreaker for the PR going through and can be discussed afterwards.

Side-note; does exporting functionality multiple times have any consequences to it?

[the remark this answers is not in the document]
Comment (omus) [reply src/TimeZones.jl]: > does exporting functionality multiple times have any consequences to it?

No it shouldn't
