### PR TITLE
Ensure CUSTOM_REGIONS get compiled

### LINKED ISSUE #305: Parsing a datetime string including "GMT" stopped working in v1.5.0
`TimeZones.ZonedDateTime` used to work prior to release 1.5.0 when GMT was included. An error referring to legacy timezones is now returned. However, I'm not aware that such legacy timezones can be specified when parsing a string. 

```julia
julia> dt_string_1 = "Sat, 31 Oct 2020 11:31:54 GMT"
"Sat, 31 Oct 2020 11:31:54 GMT"

julia> TimeZones.ZonedDateTime(dt_string_1, "e, d u Y H:M:S Z")
ERROR: ArgumentError: Unable to parse string "Sat, 31 Oct 2020 11:31:54 GMT" using format dateformat"e, d u Y H:M:S Z". The time zone "GMT" is of class `TimeZones.Class(:LEGACY)` which is currently not allowed by the mask: `TimeZones.Class(:FIXED) | TimeZones.Class(:STANDARD)`
Stacktrace:
 [1] TimeZone(::SubString{String}, ::TimeZones.Class) at C:\Users\jerem\.julia\packages\TimeZones\fr1IP\src\types\timezone.jl:65
 [2] TimeZone at C:\Users\jerem\.julia\packages\TimeZones\fr1IP\src\types\timezone.jl:46 [inlined]
 [3] ZonedDateTime(::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::Int64, ::SubString{String}) at C:\Users\jerem\.julia\packages\TimeZones\fr1IP\src\types\zoneddatetime.jl:132
 [4] parse at C:\Users\jerem\AppData\Local\Programs\Julia-1.5.2\share\julia\stdlib\v1.5\Dates\src\parse.jl:285 [inlined]
 [5] ZonedDateTime(::String, ::DateFormat{Symbol("e, d u Y H:M:S Z"),Tuple{Dates.DatePart{'e'},Dates.Delim{String,2},Dates.DatePart{'d'},Dates.Delim{Char,1},Dates.DatePart{'u'},Dates.Delim{Char,1},Dates.DatePart{'Y'},Dates.Delim{Char,1},Dates.DatePart{'H'},Dates.Delim{Char,1},Dates.DatePart{'M'},Dates.Delim{Char,1},Dates.DatePart{'S'},Dates.Delim{Char,1},Dates.DatePart{'Z'}}}) at C:\Users\jerem\.julia\packages\TimeZones\fr1IP\src\parse.jl:88
 [6] ZonedDateTime(::String, ::String; locale::String) at C:\Users\jerem\.julia\packages\TimeZones\fr1IP\src\parse.jl:101
 [7] ZonedDateTime(::String, ::String) at C:\Users\jerem\.julia\packages\TimeZones\fr1IP\src\parse.jl:101
 [8] top-level scope at REPL[96]:1

```

Base function works when specifying the presence of Z, although the notion of timezone is ignored.  This seems a viable approach for my use case. I'm just wondering whether it wouldn't be more convenient to keep supporting the parsing of GMT in `ZonedDateTime`?

```
julia> Dates.DateTime(dt_string_1, "e, d u Y H:M:S Z")
2020-10-31T11:31:54
```

### PR DESCRIPTION
**Pull request by iamed2**
Fix #305 

Issue was introduced by https://github.com/JuliaTime/TimeZones.jl/commit/07e3c9e8db4c239817653a9758e1fd2a3fb9bb89

`regions` was being redefined without the `utc` custom region, which cause the later code compiling the time zones to ignore `utc` as well. 

I did a `union!` rather than concatenating to avoid compiling anything twice.

### CODE REVIEW

**Review by mjram0s — APPROVED** [review]

**Comment by mjram0s** [comment]
Some CI jobs failing with
```
│ [ Info: Extracting 2016j tzdata archive
│ ERROR: LoadError: UndefVarError: artifact_dir not defined
```
https://travis-ci.com/github/JuliaTime/TimeZones.jl/jobs/441885262#L291

File: src/tzdata/build.jl [hunk 1]
```diff
@@ -87,7 +87,7 @@ function build(
 
         if !isempty(tz_source_dir)
             @info "Extracting $version tzdata archive"
-            regions = intersect(regions, readarchive(archive))
+            regions = union!(intersect(regions, readdir(artifact_dir)), CUSTOM_REGIONS)
```
Comment (nickrobinson251) [inline src/tzdata/build.jl:90]: did you mean to change `archive`->`artifact_dir`?

```suggestion
            regions = union!(intersect(regions, readdir(archive)), CUSTOM_REGIONS)
```

Comment (iamed2) [reply src/tzdata/build.jl:90]:
```suggestion
            regions = union!(intersect(regions, readarchive(archive)), CUSTOM_REGIONS)
```
Good catch but it should be this instead

**Review by mjram0s — APPROVED** [review]
